#!/usr/bin/env python3
"""Generate the flip site's data from the repository and the real CLI.

The flipbook replays a compact, offline-safe version of a completed public
reporting run against a scratch notebook. Every command, output, record, and
tree change is generated by ``flip``; the conversational framing is distilled
from the run whose complete notebook lives in ``flip-examples/okf-origins``.
The spec map comes from parsing SPEC.md and cross-checking it against the
generated notebook; coordinates come from ``pyproject.toml``, the tests, and
git.

Every derivation is fail-loud: a drifted spec section, a frontmatter key the
implementation no longer writes, or a CLI command that vanished raises and the
site does not build. That is the point — the site cannot quietly describe a
flip that no longer exists.

Stdlib only, and no network access. Run via ``artoo build``.
"""

from __future__ import annotations

import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
import tomllib
from datetime import datetime, timezone
from pathlib import Path

ARTIFACT = Path(__file__).resolve().parent
REPO = ARTIFACT.parent
SITE = ARTIFACT / "site"
DATA = SITE / "data"

class BuildError(RuntimeError):
    """A derivation drifted. Fail the build rather than ship a stale fact."""


# ---------------------------------------------------------------------------
# process helpers


def flip_bin() -> str:
    binary = os.environ.get("FLIP_BIN") or shutil.which("flip")
    if not binary:
        raise BuildError("flip is not on PATH; install it (uv tool install flip-notebook)")
    return binary


def run(args: list[str], cwd: Path, env: dict[str, str]) -> subprocess.CompletedProcess:
    return subprocess.run(
        args, cwd=cwd, env=env, capture_output=True, text=True, timeout=120
    )


def git(*args: str) -> str:
    try:
        out = subprocess.run(
            ["git", *args], cwd=REPO, capture_output=True, text=True, timeout=30
        )
    except (OSError, subprocess.SubprocessError):
        return ""
    return out.stdout.strip() if out.returncode == 0 else ""


# ---------------------------------------------------------------------------
# repository coordinates


def read_pyproject() -> dict:
    with (REPO / "pyproject.toml").open("rb") as handle:
        return tomllib.load(handle)


def count_tests() -> int:
    """Count test functions by parsing the test sources.

    Deliberately not ``pytest --collect-only``: the site must build in a
    checkout without the dev extras installed, and a plain ``def test_`` count
    is honest about what it measures (test functions, not coverage).
    """
    total = 0
    for path in sorted((REPO / "tests").rglob("test_*.py")):
        total += len(re.findall(r"^def test_", path.read_text(encoding="utf-8"), re.M))
    if total < 1:
        raise BuildError("counted zero tests; the test layout must have moved")
    return total


def cli_map() -> dict:
    proc = subprocess.run(
        [flip_bin(), "cli", "--json"], capture_output=True, text=True, timeout=60
    )
    if proc.returncode != 0:
        raise BuildError(f"flip cli --json failed: {proc.stderr.strip()}")
    return json.loads(proc.stdout)


# ---------------------------------------------------------------------------
# the demo notebook — the flipbook's source of truth

def snapshot_tree(root: Path) -> dict[str, float]:
    """Path -> mtime for every file in the notebook, so we can mark changes."""
    out: dict[str, float] = {}
    for path in root.rglob("*"):
        if path.is_file():
            out[path.relative_to(root).as_posix()] = path.stat().st_mtime_ns
    return out


def read_slice(path: Path, limit: int = 40) -> tuple[str, bool]:
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    if len(lines) > limit:
        return "\n".join(lines[:limit]), True
    return text.rstrip("\n"), False


# The public flipbook is based on a real agent-led reporting run rather than a
# sequence of human-authored CLI instructions.  Keep compact, dated source
# packets here so the documentation build remains deterministic and offline;
# the complete notebook, including the original captures, lives in
# lavallee/flip-examples/okf-origins.  The packets retain canonical URLs and
# only the facts exercised by the walkthrough.
DEMO_SLUG = "okf-origins"
DEMO_TITLE = "Where OKF came from and where it may go"

DEMO_FILES = {
    "okf-launch.md": """# OKF v0.1 launch — source packet

Canonical source: https://cloud.google.com/blog/products/data-analytics/how-the-open-knowledge-format-can-improve-data-sharing
Published: 2026-06-12

The authors describe OKF as formalizing Andrej Karpathy's LLM-wiki pattern
into a portable, interoperable format. They name Obsidian, Notion, Hugo,
AGENTS.md/CLAUDE.md convention files, and repositories with index and log pages
as familiar or convergent patterns.
""",
    "llm-wiki.md": """# LLM-wiki — source packet

Canonical source: https://gist.github.com/karpathy/442a6bf555914893e9891c11519de94f
Created: 2026-04-04

The idea file proposes immutable raw sources, an agent-maintained interlinked
Markdown wiki, and repository instructions/history between documents and
queries. It mentions Git and Obsidian, and relates the pattern in spirit to
Vannevar Bush's Memex.
""",
    "import-pr.json": """{
  "canonical_url": "https://github.com/GoogleCloudPlatform/knowledge-catalog/pull/28",
  "merged_at": "2026-06-12T05:02:32Z",
  "summary": "Import OKF as a single snapshot commit with no upstream git history",
  "upstream": "https://github.com/amirhormati/open-knowledge-format"
}
""",
    "spec-commits.json": """{
  "canonical_url": "https://api.github.com/repos/GoogleCloudPlatform/knowledge-catalog/commits?path=okf/SPEC.md",
  "captured": "2026-08-20",
  "commits": [
    {"date": "2026-07-24", "sha": "3fcbb9f828", "summary": "wording update"},
    {"date": "2026-07-24", "sha": "780fe9d30b", "summary": "migrate to OKF v0.2"},
    {"date": "2026-06-12", "sha": "ee67a5ca27", "summary": "snapshot import"}
  ]
}
""",
    "okf-spec.md": """# OKF v0.2 spec — source packet

Canonical source: https://github.com/GoogleCloudPlatform/knowledge-catalog/blob/main/okf/SPEC.md
Captured: 2026-08-20

Non-goals include storage, serving, query infrastructure, domain-schema
replacement, and executable packaging. "Considered and deferred" names a full
runtime protocol, attester ABI/portability/sandboxing, attestation caching, and
semantic-layer templates. Type is the only always-required key.
""",
    "issue-identity.md": """# Stable identity during refactors
Canonical source: https://github.com/GoogleCloudPlatform/knowledge-catalog/issues/120
State at capture: open. The proposal argues that path-as-identity breaks
inbound links when maintained bundles are reorganized.
""",
    "issue-routing.md": """# Agent routing by depth
Canonical source: https://github.com/GoogleCloudPlatform/knowledge-catalog/issues/93
State at capture: open. The proposal says peer-level concepts do not tell an
agent whether a page is reference, analysis, or synthesis.
""",
    "issue-links.md": """# Relationship semantics
Canonical source: https://github.com/GoogleCloudPlatform/knowledge-catalog/issues/101
State at capture: open. The proposal asks for richer semantics on otherwise
untyped Markdown links.
""",
    "issue-retrieval.md": """# Retrieval at large scale
Canonical source: https://github.com/GoogleCloudPlatform/knowledge-catalog/discussions/217
State at capture: unanswered. The discussion asks whether very large bundles
need vector or hybrid retrieval and what enterprise architecture is intended.
""",
    "issue-composition.md": """# Cross-bundle composition
Canonical source: https://github.com/GoogleCloudPlatform/knowledge-catalog/issues/175
State at capture: open. The proposal asks for an external-bundle registry and
lists unresolved mounting, integrity, and multi-source semantics.
""",
    "issue-orientation.md": """# Purpose and audience orientation
Canonical source: https://github.com/GoogleCloudPlatform/knowledge-catalog/issues/96
State at capture: open. The proposal says domain concepts alone do not tell a
downstream agent the task, purpose, or audience of a bundle.
""",
    "roadmap-check.json": """{
  "captured": "2026-08-20",
  "surfaces": {
    "repository_root_roadmap_file": false,
    "okf_directory_roadmap_file": false,
    "all_state_milestones": []
  },
  "excluded": ["project boards: unavailable to this run"],
  "planning_signals": [
    "the current spec names work deferred to a future revision",
    "the v0.2 release says community proposals shaped the release",
    "active issues and pull requests contain candidate extensions"
  ]
}
""",
    "conversation.md": """# Conversation

**Human:** let's use flip to track the origins of OKF and what precedents it
builds on, what critiques / gaps currently exist, and whether there's any
evidence of a roadmap or other planning.

**Agent:** The public chain runs from LLM-wiki to a history-free June snapshot
import and July v0.2. The visible gaps cluster around identity, routing,
relationships, retrieval, and composition. No formal roadmap appeared on the
checked file and milestone surfaces, but the spec's deferred list and active
proposals are planning evidence short of a schedule.
""",
}


def step_plan() -> list[dict]:
    """A natural reporting exchange; CLI work is a receipt, not dialogue."""
    return [
        {
            "id": "assignment",
            "say": (
                "let's use flip to track the origins of OKF and what precedents "
                "it builds on, what critiques / gaps currently exist, and whether "
                "there's any evidence of a roadmap or other planning."
            ),
            "reply": (
                "I’ll run that as a bounded research review: trace the public "
                "origin chain, keep accepted spec separate from proposals, and "
                "make any roadmap null name the exact surfaces checked."
            ),
            "act": "The assignment",
            "title": "Open a reporting notebook",
            "narrative": (
                "The person supplies the reporting question, not a sequence of "
                "database chores. The agent chooses the research-review profile "
                "and the notebook starts as ordinary Markdown."
            ),
            "spec": "4",
            "commands": [["new", DEMO_SLUG, "--kind", "research-review", "--title", DEMO_TITLE, "--visibility", "public"]],
            "cwd": "root",
            "record": {
                "kind": "file",
                "path": "index.md",
                "lang": "markdown",
                "caption": "The manifest: one portable OKF bundle, before the research begins.",
            },
        },
        {
            "id": "frame",
            "say": "",
            "reply": (
                "I’ve turned the assignment into four watched questions and "
                "opened a session, so the investigation can outlive this chat."
            ),
            "act": "Reporting",
            "title": "Frame the investigation",
            "narrative": (
                "The agent decomposes one assignment into origin, precedent, gap, "
                "and planning questions. Each is a page with an immutable id and "
                "a surface that could resolve it."
            ),
            "spec": "7",
            "commands": [
                ["session", "start", "okf-origins", "--model", "agent-harness", "--tools", "web-search", "--tools", "github", "--tools", "flip"],
                ["question", "add", "What are the traceable origins of OKF?", "--resolves-via", "launch material and repository history"],
                ["question", "add", "What precedents does OKF build on?", "--resolves-via", "author statements and the named predecessor"],
                ["question", "add", "What critiques and gaps are visible now?", "--resolves-via", "spec boundaries and public proposals"],
                ["question", "add", "Is there evidence of a roadmap or other planning?", "--resolves-via", "repository files, milestones, spec deferrals, and proposals"],
                ["log", "started: trace OKF origins, gaps, and planning evidence"],
            ],
            "record": {
                "kind": "glob",
                "pattern": "sessions/*.md",
                "lang": "markdown",
                "caption": "The session records the actor, model surface, tools, and goal.",
            },
        },
        {
            "id": "lineage",
            "say": "",
            "reply": (
                "The direct lineage is explicit: OKF’s launch account says it "
                "formalizes Karpathy’s earlier LLM-wiki pattern. I’ve kept the "
                "deeper Memex connection second-order, because LLM-wiki makes it; "
                "the OKF launch post does not."
            ),
            "act": "Reporting",
            "title": "Trace the declared precedent",
            "narrative": (
                "The agent captures before citing, grades after reading, and uses "
                "an attribution test for claims about what one document says. "
                "A second witness cannot exist for the contents of one document."
            ),
            "spec": "7",
            "commands": [
                ["add-source", "../okf-launch.md", "--note", "dated public-source packet; full capture in flip-examples"],
                ["grade", "F1", "--independence", "derivative", "--basis", "synthesis", "--method", "compact packet from the held launch post"],
                ["grade", "F1", "--explain"],
                ["add-source", "../llm-wiki.md", "--note", "dated public-source packet; full capture in flip-examples"],
                ["grade", "F2", "--independence", "derivative", "--basis", "synthesis", "--method", "compact packet from the held idea file"],
                ["claim", "add", "OKF's launch account says v0.1 formalizes the LLM-wiki pattern", "--about", "F1", "--load-bearing"],
                ["claim", "test", "C1", "--probe", "attribution", "--error", "the launch account names no LLM-wiki lineage", "--would-detect", "LLM-wiki is absent or described as unrelated", "--if-absent", "the account says OKF formalizes LLM-wiki", "--against", "F1", "--result", "survived"],
                ["claim", "status", "C1", "verified"],
                ["claim", "add", "LLM-wiki predates the OKF launch and names Memex as a deeper precedent", "--about", "F2", "--load-bearing"],
                ["claim", "test", "C2", "--probe", "attribution", "--error", "the idea file lacks the date or Memex connection", "--would-detect", "either element is absent", "--if-absent", "both appear in the held file", "--against", "F2", "--result", "survived"],
                ["claim", "status", "C2", "verified"],
                ["question", "answer", "Q2", "--note", "Direct precedent: LLM-wiki. Familiar substrate: Markdown/YAML/Git and wiki tools. Memex is second-order lineage."],
            ],
            "record": {
                "kind": "glob",
                "pattern": "claims/*.md",
                "lang": "markdown",
                "caption": "A document-subject claim earns verification through a severe attribution test, not fake corroboration.",
            },
        },
        {
            "id": "history-gap",
            "say": "",
            "reply": (
                "There’s a real break in the origin record. The first public "
                "GoogleCloudPlatform commit is a June snapshot import whose PR "
                "explicitly says upstream history was not preserved; the public "
                "spec history then has only two July v0.2 changes."
            ),
            "act": "Reporting",
            "title": "Keep the missing history visible",
            "narrative": (
                "A notebook can hold a confident finding and its boundary at the "
                "same time. The import record establishes what was omitted; the "
                "commit endpoint establishes what the public history does contain."
            ),
            "spec": "5",
            "commands": [
                ["add-source", "../import-pr.json", "--note", "public PR metadata packet"],
                ["grade", "F3", "--independence", "self-reported", "--basis", "official-record", "--method", "merged pull-request record"],
                ["add-source", "../spec-commits.json", "--note", "GitHub commits endpoint packet"],
                ["grade", "F4", "--independence", "independent", "--basis", "platform-data", "--method", "GitHub commits endpoint", "--base-defined"],
                ["claim", "add", "The public OKF spec history contains a June snapshot import and two July v0.2 changes", "--source", "F4", "--load-bearing"],
                ["claim", "status", "C3", "verified"],
                ["claim", "add", "The import PR says upstream Git history was not preserved", "--about", "F3", "--load-bearing"],
                ["claim", "test", "C4", "--probe", "attribution", "--error", "the PR preserves or does not discuss upstream history", "--would-detect", "a subtree import or silence", "--if-absent", "the PR calls it a history-free snapshot", "--against", "F3", "--result", "survived"],
                ["claim", "status", "C4", "verified"],
                ["question", "answer", "Q1", "--note", "The traceable chain ends at a history-free June snapshot before the July v0.2 changes."],
            ],
            "record": {
                "kind": "glob",
                "pattern": "claims/*.md",
                "lang": "markdown",
                "caption": "The omission stays attached to the origin finding instead of disappearing from the summary.",
            },
        },
        {
            "id": "gap-lead",
            "say": "",
            "reply": (
                "The spec names deliberate boundaries, and the first public "
                "proposal points to a stable-identity gap. That is enough to open "
                "the line of inquiry—not enough to call it a recurring cluster."
            ),
            "act": "Reporting",
            "title": "Separate a lead from a finding",
            "narrative": (
                "The spec's deliberate boundaries stay separate from criticism. "
                "One independently authored proposal can name a lead, but the "
                "research-review profile will not let it stand in for a cluster."
            ),
            "spec": "7",
            "commands": [
                ["add-source", "../okf-spec.md", "--note", "current spec packet"],
                ["grade", "F5", "--independence", "self-reported", "--basis", "official-record", "--method", "current normative spec"],
                ["claim", "add", "OKF deliberately leaves query infrastructure and runtime packaging outside the format and defers several runtime concerns", "--about", "F5", "--load-bearing"],
                ["claim", "test", "C5", "--probe", "attribution", "--error", "the spec does not name those boundaries", "--would-detect", "the non-goal and deferred lists omit them", "--if-absent", "the lists name them directly", "--against", "F5", "--result", "survived"],
                ["claim", "status", "C5", "verified"],
                ["add-source", "../issue-identity.md", "--note", "public proposal packet"],
                ["grade", "F6", "--independence", "independent", "--basis", "single-operator", "--method", "public proposal at its canonical URL"],
                ["claim", "add", "Visible proposals cluster around identity, routing, relationships, retrieval, and composition", "--source", "F6", "--load-bearing"],
            ],
            "record": {
                "kind": "glob",
                "pattern": "claims/*.md",
                "lang": "markdown",
                "caption": "The cluster begins as an asserted lead with one source, not a finished finding.",
            },
        },
        {
            "id": "refused",
            "say": "",
            "reply": (
                "I tried the promotion at the point where the evidence was still "
                "thin. flip refused: one independent proposal does not meet this "
                "notebook’s two-source bar. I need to corroborate the pattern."
            ),
            "act": "Reporting",
            "title": "Let the evidence gate say no",
            "narrative": (
                "The failed command is part of the demonstration. The claim stays "
                "asserted, the process exits non-zero, and the output names every "
                "legitimate path forward instead of accepting confidence as evidence."
            ),
            "spec": "7",
            "commands": [["claim", "status", "C6", "verified"]],
            "expect_failure": True,
            "record": {
                "kind": "stdout",
                "lang": "text",
                "caption": "A real refusal from the CLI; the claim remains asserted.",
            },
        },
        {
            "id": "gaps",
            "say": "",
            "reply": (
                "After checking five more independently authored proposals, the "
                "pattern holds: identity, routing, relationships, retrieval, and "
                "composition. These remain proposals—not accepted OKF commitments."
            ),
            "act": "Reporting",
            "title": "Corroborate the gap map",
            "narrative": (
                "The synthesis now rests on six separately authored public threads. "
                "The agent adds them to the existing claim, then the same gate that "
                "refused it earlier allows verification."
            ),
            "spec": "7",
            "commands": [
                *sum((
                    [["add-source", f"../{name}", "--note", "public proposal packet"],
                     ["grade", f"F{number}", "--independence", "independent", "--basis", "single-operator", "--method", "public proposal at its canonical URL"]]
                    for number, name in enumerate((
                        "issue-routing.md", "issue-links.md", "issue-retrieval.md",
                        "issue-composition.md", "issue-orientation.md"
                    ), start=7)
                ), []),
                ["claim", "source", "add", "C6", "F7", "F8", "F9", "F10", "F11"],
                ["claim", "status", "C6", "verified"],
                ["question", "answer", "Q3", "--note", "Five recurring gap classes, with spec boundaries kept separate from contributor proposals."],
            ],
            "record": {
                "kind": "glob",
                "pattern": "claims/*.md",
                "lang": "markdown",
                "caption": "The cluster claim clears the bar through six independent proposal records.",
            },
        },
        {
            "id": "roadmap",
            "say": "",
            "reply": (
                "I found no formal roadmap on the checked file and milestone "
                "surfaces, but I did find planning: named deferred work, a release "
                "shaped by proposals, and active extension designs. The honest "
                "answer is direction of travel without a public schedule."
            ),
            "act": "Reporting",
            "title": "Test the roadmap null",
            "narrative": (
                "Absence is useful only with coverage attached. The decision page "
                "excludes an unobservable project board, while a separate positive "
                "claim records the weaker planning signals that were found."
            ),
            "spec": "7",
            "commands": [
                ["add-source", "../roadmap-check.json", "--note", "bounded repository-surface check"],
                ["grade", "F12", "--independence", "independent", "--basis", "platform-data", "--method", "repository contents and milestones endpoints", "--base-defined"],
                ["claim", "add", "No formal public roadmap was found on the checked root, okf directory, or milestone surfaces", "--source", "F12", "--absent-from", "named_surfaces", "--surface", "repository root contents", "--surface", "okf directory contents", "--surface", "all-state milestones", "--load-bearing"],
                ["claim", "status", "C7", "verified"],
                ["claim", "add", "There is public planning evidence short of a formal roadmap", "--source", "F12", "--load-bearing"],
                ["claim", "status", "C8", "verified"],
                ["decide", "--question", "How far can the roadmap null reach?", "--decision", "Only the three checked repository surfaces", "--why", "Project-board contents were not observable", "--rejected", "Infer that no planning exists"],
                ["question", "answer", "Q4", "--note", "No formal roadmap on checked surfaces; positive planning signals exist without dates or sequence.", "--reopen-when", "a roadmap, milestone, dated release plan, or observable project board appears"],
            ],
            "record": {
                "kind": "glob",
                "pattern": "claims/*.md",
                "lang": "markdown",
                "caption": "A bounded null and a positive planning claim coexist; neither is stretched to replace the other.",
            },
        },
        {
            "id": "handoff",
            "say": "",
            "reply": (
                "The notebook is ready: the assignment, periodic findings, and "
                "final answer are captured as a transcript; the source and claim "
                "records sit underneath it for anyone who wants to audit or continue."
            ),
            "act": "The handoff",
            "title": "Keep the conversation and audit the record",
            "narrative": (
                "The transcript is ordinary custody, not a screenshot. The session "
                "closes with a cold-pickup summary, then doctor checks the bundle. "
                "The full 18-source notebook is linked beside this walkthrough."
            ),
            "spec": "8",
            "ensure_dirs": ["drafts"],
            "commands": [
                ["session", "transcript", "okf-origins", "--file", "../conversation.md", "--participant", "human:maintainer", "--participant", "agent:harness", "--model", "agent-harness"],
                ["transcript", "excerpt", "T1", "--lines", "3-7", "--label", "assignment"],
                ["log", "handoff: origins bounded; gaps mapped; roadmap null scoped"],
                ["session", "end", "okf-origins", "--summary", "Eight verified claims; four assignment questions answered; transcript captured."],
                ["doctor"],
            ],
            "record": {
                "kind": "glob",
                "pattern": "references/*.md",
                "lang": "markdown",
                "caption": "The transcript is a T# source under the same custody rules as every other input.",
            },
        },
        {
            "id": "answer",
            "say": "",
            "reply": (
                "Bottom line: OKF is a recent interoperability layer over the "
                "agent-maintained-wiki pattern, with a public history that starts "
                "at a snapshot rather than at inception. Its permissive core is "
                "both the portability win and the source of current pressure around "
                "identity, routing, relationships, retrieval, composition, and "
                "enforcement. Planning is visible; a public schedule is not."
            ),
            "act": "The handoff",
            "title": "Read the hot view",
            "narrative": (
                "The concise answer is a projection over the durable notebook. "
                "A future agent can start from the answered questions and reopen "
                "conditions instead of searching the same ground again."
            ),
            "spec": "10",
            "commands": [["show", "--claims"]],
            "record": {
                "kind": "stdout",
                "lang": "text",
                "caption": "The hot view is computed from the notebook; the pages and ledgers remain canonical.",
            },
        },
    ]


def build_flipbook(env_base: dict[str, str]) -> dict:
    binary = flip_bin()
    with tempfile.TemporaryDirectory(prefix="flip-site-") as tmp:
        workspace = Path(tmp)
        home = workspace / "flip-home"
        home.mkdir()
        env = {
            **env_base,
            "FLIP_HOME": str(home),          # never touch the operator's ~/.flip
            "FLIP_ACTOR": "agent:harness",  # deterministic attribution
            "NO_COLOR": "1",
            "COLUMNS": "88",
        }
        for name, body in DEMO_FILES.items():
            (workspace / name).write_text(body, encoding="utf-8")

        notebook = workspace / DEMO_SLUG
        steps: list[dict] = []
        previous: dict[str, float] = {}

        for index, plan in enumerate(step_plan(), start=1):
            cwd = workspace if plan.get("cwd") == "root" else notebook
            for rel in plan.get("ensure_dirs", []):
                (notebook / rel).mkdir(parents=True, exist_ok=True)
            outputs: list[str] = []
            code = 0
            for argv in plan["commands"]:
                proc = run([binary, *argv], cwd=cwd, env=env)
                chunk = (proc.stdout or "") + (proc.stderr or "")
                outputs.append(chunk.rstrip("\n"))
                code = proc.returncode
                if code != 0 and not (plan.get("expect_failure") or plan.get("allow_failure")):
                    raise BuildError(
                        f"step {plan['id']}: `flip {' '.join(argv)}` exited {code}\n{chunk}"
                    )
            if plan.get("expect_failure") and code == 0:
                raise BuildError(
                    f"step {plan['id']} expected a refusal but the command succeeded — "
                    "the verification bar may have been weakened"
                )

            current = snapshot_tree(notebook)
            tree = []
            for path in sorted(current):
                if path not in previous:
                    state = "added"
                elif current[path] != previous[path]:
                    state = "changed"
                else:
                    state = "same"
                tree.append({"path": path, "state": state})
            previous = current

            record = dict(plan["record"])
            spec = record.pop("kind")
            if spec == "stdout":
                body = "\n\n".join(chunk for chunk in outputs if chunk) or "(no output)"
                limit = record.pop("truncate", 0)
                if limit:
                    lines = body.splitlines()
                    if len(lines) > limit:
                        body = "\n".join(lines[:limit])
                        record["truncated"] = True
                record["text"] = body
                record["path"] = "stdout"
            else:
                if spec == "glob":
                    # index.md in each directory is a generated listing, never an
                    # entity page — and the entity we mean is the one this step
                    # just touched, so select by mtime rather than by name.
                    matches = [
                        path
                        for path in notebook.glob(record.pop("pattern"))
                        if path.name != "index.md"
                    ]
                    if not matches:
                        raise BuildError(f"step {plan['id']}: record glob matched nothing")
                    target = max(matches, key=lambda p: p.stat().st_mtime_ns)
                else:
                    target = notebook / record["path"]
                if not target.exists():
                    raise BuildError(f"step {plan['id']}: record path {target} is missing")
                if spec == "jsonl":
                    lines = [
                        line
                        for line in target.read_text(encoding="utf-8").splitlines()
                        if line.strip()
                    ]
                    record["text"] = json.dumps(json.loads(lines[-1]), indent=2)
                else:
                    text, truncated = read_slice(target)
                    record["text"] = text
                    if truncated:
                        record["truncated"] = True
                record["path"] = target.relative_to(notebook).as_posix()

            steps.append(
                {
                    "n": index,
                    "id": plan["id"],
                    "say": plan.get("say", ""),
                    "reply": plan.get("reply", ""),
                    "act": plan["act"],
                    "title": plan["title"],
                    "narrative": plan["narrative"],
                    "spec": plan["spec"],
                    # Shell-quoted: the site shows a copy button beside these, so
                    # what is displayed has to be what you can actually paste.
                    "commands": ["flip " + shlex.join(argv) for argv in plan["commands"]],
                    "command_outputs": [
                        {
                            "command": "flip " + shlex.join(argv),
                            "stdout": output,
                        }
                        for argv, output in zip(plan["commands"], outputs, strict=True)
                    ],
                    "stdout": "\n\n".join(chunk for chunk in outputs if chunk),
                    "exit_code": code,
                    "refused": bool(plan.get("expect_failure")),
                    "tree": tree,
                    "record": record,
                }
            )

        # Cross-check the spec map against what the implementation really wrote.
        frontmatter = harvest_frontmatter(notebook)

        # The flip-render/2 projection of this same scratch notebook, taken
        # before the temp directory goes away — the canonical data source
        # for site/notebook.html.
        export = export_demo_notebook(binary, notebook, env)

    return {"steps": steps, "frontmatter_seen": frontmatter, "export": export}


def export_demo_notebook(binary: str, notebook: Path, env: dict[str, str]) -> dict:
    """Run the real `flip export json --render-version 2` against the scratch
    demo notebook while it still exists on disk, and return the parsed
    flip-render/2 projection.

    This is the canonical data source for notebook.html: every source,
    claim, question, decision, session, and log line on that page comes from
    this one call, not from anything hand-authored. Fails loud if the export
    itself fails, or if it does not carry the contract this site's notebook
    viewer was built against.

    Before exporting, the demo's WORK gets written the way an agent would
    write it — a findings page in analysis/ — because a notebook is the
    completed/in-progress work AND its dependent sources, and the viewer
    should show both.
    """
    analysis = notebook / "analysis"
    analysis.mkdir(exist_ok=True)
    (analysis / "findings.md").write_text(
        "---\n"
        "type: Finding\n"
        "title: Where OKF came from and where it may go\n"
        "---\n\n"
        "# Bottom line\n\n"
        "OKF's declared direct precedent is LLM-wiki [C1-C2], but its public\n"
        "GoogleCloudPlatform history begins at a snapshot import that omitted\n"
        "the upstream Git history [C3-C4]. The current pressure points cluster\n"
        "around stable identity, agent routing, relationship semantics,\n"
        "large-bundle retrieval, and cross-bundle composition [C5-C6].\n\n"
        "No formal roadmap appeared on the three checked file and milestone\n"
        "surfaces [C7]. Planning is still visible through named deferred work\n"
        "and active proposals [C8]: direction of travel, not a public schedule.\n",
        encoding="utf-8",
    )
    proc = run(
        [binary, "export", "json", "--render-version", "2", "--include-private", "--out", "-"],
        cwd=notebook,
        env=env,
    )
    if proc.returncode != 0:
        raise BuildError(
            f"`flip export json --render-version 2` exited {proc.returncode}:\n"
            f"{(proc.stdout or '') + (proc.stderr or '')}"
        )
    try:
        payload = json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise BuildError(
            f"`flip export json --render-version 2` did not emit valid JSON: {exc}"
        ) from exc
    if payload.get("contract") != "flip-render/2":
        raise BuildError(
            "expected the flip-render/2 contract from `flip export json "
            f"--render-version 2`, got {payload.get('contract')!r}"
        )
    return payload


def harvest_frontmatter(notebook: Path) -> dict[str, list[str]]:
    """Collect the frontmatter keys each entity type actually carries."""
    seen: dict[str, set[str]] = {}
    for path in notebook.rglob("*.md"):
        text = path.read_text(encoding="utf-8", errors="replace")
        if not text.startswith("---\n"):
            continue
        end = text.find("\n---", 4)
        if end == -1:
            continue
        block = text[4:end]
        keys = re.findall(r"^([A-Za-z_][A-Za-z0-9_]*):", block, re.M)
        kind = "Manifest"
        for line in block.splitlines():
            if line.startswith("type:"):
                kind = line.split(":", 1)[1].strip().strip("\"'")
                break
        seen.setdefault(kind, set()).update(keys)
    return {kind: sorted(keys) for kind, keys in sorted(seen.items())}


# ---------------------------------------------------------------------------
# the spec map


ENTITIES = [
    {
        "type": "Source",
        "id_prefix": "P# A# F# T# S#",
        "dir": "references/",
        "spec": "5",
        "summary": "An external artifact we captured, and our judgment of it. A kept conversation is one of these too.",
        "judgment": True,
        "keys": ["type", "id", "aliases", "title", "resource", "local", "grade", "independence", "support", "status", "medium", "excerpts"],
    },
    {
        "type": "Claim",
        "id_prefix": "C#",
        "dir": "claims/",
        "spec": "7",
        "summary": "A discrete assertion, its sources, how far it has earned trust, and what has been asked of it.",
        "judgment": True,
        "keys": ["type", "id", "aliases", "description", "status", "load_bearing", "sources", "independent_corroboration", "tests", "first_asserted", "generated"],
    },
    {
        "type": "Decision",
        "id_prefix": "D#",
        "dir": "decisions/",
        "spec": "7",
        "summary": "A resolved fork and — the payload — why it was resolved that way.",
        "judgment": False,
        "keys": ["type", "id", "aliases", "question", "alternatives_rejected", "generated"],
    },
    {
        "type": "Question",
        "id_prefix": "Q#",
        "dir": "questions/",
        "spec": "7",
        "summary": "Something that needs answering, re-posable without losing the earlier wording.",
        "judgment": False,
        "keys": ["type", "id", "aliases", "status", "generated"],
    },
    {
        "type": "Work Session",
        "id_prefix": "dated",
        "dir": "sessions/",
        "spec": "8",
        "summary": "One human or agent working episode: generated {by, at}, model, tools, outputs.",
        "judgment": False,
        "keys": ["type", "generated", "model", "tools", "started"],
    },
]

LEDGERS = [
    {
        "path": "sources/_provenance.jsonl",
        "spec": "5",
        "label": "Capture log",
        "summary": "One line per acquisition: url, local path, sha256, bytes, tool, strategy, actor. The fixity record.",
    },
    {
        "path": "derived/_derivations.jsonl",
        "spec": "8",
        "label": "Derivation log",
        "summary": "Inputs to tool and parameters to outputs, with hashes, written by flip extract. Records the extraction method, because a quotation recovered by OCR is not the same evidence as one lifted from a publisher's text layer.",
    },
    {
        "path": "log/log.jsonl",
        "spec": "8",
        "label": "Work log",
        "summary": "Fetched X, ran Y, hit wall Z. The generated newest-first view is log.md at the bundle root.",
    },
    {
        "path": "log/passed.jsonl",
        "spec": "8",
        "label": "Passed ledger",
        "summary": "Negative evidence — considered and rejected, with the reason. Prevents rediscovery loops.",
    },
]

LIFECYCLE = [
    {
        "stage": "captured",
        "act": "flip add-source",
        "spec": "5",
        "gains": "Local bytes in sources/raw/, hashed, with a provenance line.",
        "worth": "Custody. Nothing else — the page opens at grade ?.",
    },
    {
        "stage": "judged",
        "act": "flip grade",
        "spec": "5",
        "gains": "grade, independence, freshness — recorded by a named actor after reading.",
        "worth": "Now it can count toward a claim. Ungraded sources corroborate nothing.",
    },
    {
        "stage": "cited",
        "act": "flip claim add --source",
        "spec": "7",
        "gains": "An edge from a claim, and a regenerated citation block.",
        "worth": "The claim enters as asserted, whatever the source's grade.",
    },
    {
        "stage": "corroborating",
        "act": "flip claim source add",
        "spec": "7",
        "gains": "independent_corroboration, recomputed from the judged sources present.",
        "worth": "Counted, never trusted from the page. Doctor flags drift.",
    },
    {
        "stage": "verified",
        "act": "flip claim status … verified",
        "spec": "7",
        "gains": "The status, if and only if the profile's bar is met.",
        "worth": "Refused with a non-zero exit otherwise. Or earned by an adversarial or recomputation record.",
    },
    {
        "stage": "tested",
        "act": "flip claim test",
        "spec": "7",
        "gains": "tests: — the error a probe looked for, how it would have shown up, and what it would have shown instead.",
        "worth": "exposure, derived on read and never stored. A severe test that found the error refuses verified whatever the count says.",
    },
]

PROFILES = [
    ("ledger", "Bibliography or source spine.", "references/"),
    ("scout", "Screen an angle fast, editor lens active.", "hypotheses with falsifiers · decisions/ · passed ledger"),
    ("research-review", "Question-organised survey, heading for publication.", "claims/ · sessions/ · drafts/ · full custody"),
    ("engagement", "Confidential client work.", "research-review + confidential policy + citation rule + HANDOFF.md"),
    ("data-investigation", "Dataset-first reporting.", "derivation ledger · ingest scripts · frozen data contracts"),
    ("pursuit", "One question under pursuit.", "questions/ · claims/ · a dated question plan with a stop rule"),
]


def github_anchor(heading: str) -> str:
    """GitHub's heading-anchor slug, because that is where the links land.

    GitHub lowercases, deletes punctuation *without* substituting a separator
    (so ``index.md`` becomes ``indexmd`` and an em dash simply vanishes,
    leaving the two spaces around it to become two hyphens), then turns spaces
    into hyphens. A naive ``[^a-z0-9]+ -> -`` produces anchors that 404.
    """
    text = heading.lower()
    text = re.sub(r"[^\w\s-]", "", text, flags=re.UNICODE)
    return text.replace(" ", "-")


def parse_spec_sections() -> dict[str, dict]:
    """Map section number -> {title, anchor} from SPEC.md's own headings."""
    sections: dict[str, dict] = {}
    for line in (REPO / "SPEC.md").read_text(encoding="utf-8").splitlines():
        match = re.match(r"^## (\d+)\. (.+)$", line)
        if match:
            number, title = match.group(1), match.group(2).strip()
            sections[number] = {
                "number": number,
                "title": title,
                "anchor": github_anchor(f"{number}. {title}"),
            }
    if not sections:
        raise BuildError("parsed no sections out of SPEC.md")
    return sections


def build_spec(sections: dict[str, dict], frontmatter_seen: dict[str, list[str]]) -> dict:
    for entity in ENTITIES:
        if entity["spec"] not in sections:
            raise BuildError(f"entity {entity['type']} cites missing SPEC section {entity['spec']}")
        observed = set(frontmatter_seen.get(entity["type"], []))
        if not observed:
            raise BuildError(
                f"the demo notebook produced no {entity['type']} page; the spec map "
                "cannot be cross-checked against the implementation"
            )
        # Every key we advertise must be one the implementation really writes.
        # Conditional keys are exempt: they appear only when the capture kind or
        # the command supplies them (a copied local file has no `resource` URL).
        optional = {"model", "tools", "alternatives_rejected", "resource"}
        missing = [k for k in entity["keys"] if k not in observed and k not in optional]
        if missing:
            raise BuildError(
                f"{entity['type']} pages no longer carry {missing}; update the spec map"
            )
        entity["observed_keys"] = sorted(observed)

    for item in [*LEDGERS, *LIFECYCLE]:
        if item["spec"] not in sections:
            raise BuildError(f"missing SPEC section {item['spec']}")

    shipped = sorted(p.stem for p in (REPO / "src" / "flip" / "profiles").glob("*.toml"))
    declared = sorted(name for name, _, _ in PROFILES)
    if shipped != declared:
        raise BuildError(f"profiles drifted: shipped {shipped}, site declares {declared}")

    return {
        "sections": list(sections.values()),
        "entities": ENTITIES,
        "ledgers": LEDGERS,
        "lifecycle": LIFECYCLE,
        "profiles": [
            {"id": name, "intent": intent, "requires": requires}
            for name, intent, requires in PROFILES
        ],
    }


# ---------------------------------------------------------------------------


def main() -> int:
    env_base = {k: v for k, v in os.environ.items() if k not in {"FLIP_NOTEBOOK", "FLIP_ACTOR", "FLIP_HOME"}}
    project = read_pyproject()["project"]
    sections = parse_spec_sections()

    print("· running the real CLI to generate flipbook frames")
    flipbook = build_flipbook(env_base)

    print("· cross-checking the spec map against the generated notebook")
    spec = build_spec(sections, flipbook.pop("frontmatter_seen"))
    demo_notebook = flipbook.pop("export")

    stamp = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    skills = sorted(p.name for p in (REPO / "src" / "flip" / "skills").iterdir() if p.is_dir())
    spec_status = ""
    for line in (REPO / "SPEC.md").read_text(encoding="utf-8").splitlines()[:6]:
        if line.startswith("**Status:**"):
            spec_status = line.split("**Status:**", 1)[1].strip().replace("·", "·")
            break

    coordinates = {
        "generated": stamp,
        "version": project["version"],
        "revision": git("rev-parse", "--short", "HEAD") or "unknown",
        "requires_python": project.get("requires-python", ""),
        "dependencies": project.get("dependencies", []),
        "license": "MIT",
        "package": project["name"],
        "tests": count_tests(),
        "spec_status": spec_status,
        "spec_lines": len((REPO / "SPEC.md").read_text(encoding="utf-8").splitlines()),
        "skills": skills,
        "cli": cli_map(),
    }

    DATA.mkdir(parents=True, exist_ok=True)
    for name, global_name, payload in (
        ("flip", "__FLIP_META__", coordinates),
        (
            "flipbook",
            "__FLIP_BOOK__",
            {
                "generated": stamp,
                "notebook": {"slug": DEMO_SLUG, "title": DEMO_TITLE, "kind": "research-review"},
                **flipbook,
            },
        ),
        ("spec", "__FLIP_SPEC__", {"generated": stamp, **spec}),
        ("demo-notebook", "__FLIP_NOTEBOOK__", demo_notebook),
    ):
        body = json.dumps(payload, indent=2, sort_keys=False)
        (DATA / f"{name}.json").write_text(body + "\n", encoding="utf-8")
        # A file:// page cannot fetch() its own JSON, so ship a script loader
        # beside it — the same trick artoo uses for provenance.json.
        (DATA / f"{name}.js").write_text(
            f"window.{global_name} = {body};\n", encoding="utf-8"
        )
        print(f"· wrote site/data/{name}.json + {name}.js")

    commands = sum(len(s["commands"]) for s in flipbook["steps"])
    print(
        f"built from flip {coordinates['version']} at {coordinates['revision']}: "
        f"{len(flipbook['steps'])} frames, {commands} real commands, "
        f"{coordinates['tests']} tests, {len(spec['sections'])} spec sections"
    )
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except BuildError as exc:
        print(f"build failed: {exc}", file=sys.stderr)
        sys.exit(1)
